# Artifact Hub repository metadata file
repositoryID: 94eedfc1-e8df-4f3f-81ba-138b632c41a2
owners: # (optional, used to claim repository ownership)
  - name: Apache Solr PMC
    email: private@lucene.apache.org
